### ISSUE TITLE
Typing Hono for createOpenApiDocument

### ISSUE THREAD

**Issue by BradNut** [paolostyle/hono-zod-openapi#2]
Currently if you pass a hono object that is typed with it's own type variables, not created passing a `new Hono()`, there are type errors. Given we are no longer passing a Hono object of type `BlankEnv`.

For example:
```
  const AppBindings = {
    Variables: {
      //
    }
  }

  const app = new Hono<AppBindings>({ strict: false }).basePath('/api');

  createOpenApiDocument(app, {
    info: {
      title: 'Example API',
      version: '1.0.0',
    },
  });
```

This results in `createOpenApiDocument` stating:
`Type Hono<AppBindings, BlankSchema, '/'> is not assignable to type Hono<BlankEnv, BlankSchema, '/'>`

Any idea how to correctly type this?

**Comment by paolostyle** [comment]
I haven't handled this case in the function's signature, I will have to update it. I should have a moment to do it this weekend. You can temporarily just cast the parameter to `unknown as Hono` or even `any` and remove it after the update.

**Comment by BradNut** [comment]
@paolostyle, sounds good. Thank you! Look forward to the update.

**Comment by BradNut** [comment]
Working for me now! Thank you @paolostyle!
