### ISSUE TITLE
Publish to JSR for better Deno usage

### ISSUE THREAD

**Issue by AlaaZorkane** [paolostyle/hono-zod-openapi#4]
Hey! Love the work on the package, it's becoming my way to go on using zod-openapi on hono!

I would like to see the package published to JSR: https://jsr.io/.

It should be _relatively_ easy, as this package is already ESM.

Suggested starting point: https://jsr.io/docs/publishing-packages
Related: https://deno.com/blog/hono-on-jsr

Thank you!

**Comment by paolostyle** [comment]
The package has been published under https://jsr.io/@paolostyle/hono-zod-openapi

I still need to improve some things (see #6, #7, #8) but we'll get there!

**Comment by AlaaZorkane** [comment]
Thank you for the quick response! Awesome 🙌
